# Generated by Django 2.0.2 on 2018-04-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('levelId', models.AutoField(primary_key=True, serialize=False)),
                ('squares', models.IntegerField()),
                ('positions', models.TextField()),
            ],
        ),
    ]
